import { glob } from "astro/loaders";
import { defineCollection, z } from "astro:content";

const bonuses = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/bonuses" }),
  schema: z.object({
    title: z.string(),
    slug: z.string().optional(),
    description: z.string(),
    seoTitle: z.string().optional(),
    casino: z.string().optional(),
    bonus: z.string().optional(),
    code: z.string().optional(),
    verified: z.boolean().optional(),
    publishDate: z.coerce.string().optional(),
    publishedAt: z.coerce.string().optional(),
    updatedAt: z.coerce.string().optional(),
    lastModified: z.coerce.string().optional(),
    bonusType: z.string().optional(),
    contentType: z.string().optional(),
    tags: z.array(z.string()).optional(),
    image: z.string().optional(),
    imageAlt: z.string().optional(),
    imageWidth: z.number().optional(),
    imageHeight: z.number().optional(),
    imageLoading: z.string().optional(),
    logo: z.string().optional(),
    author: z.string().optional(),
    authorSlug: z.string().optional(),
    canonical: z.string().optional(),
    schema_jsonld: z.union([z.array(z.any()), z.record(z.any()), z.string()]).optional(),
    // Review specific
    rating: z.number().optional(),
    ourRating: z.number().optional(),
    pros: z.union([z.string(), z.array(z.string())]).optional(),
    cons: z.union([z.string(), z.array(z.string())]).optional(),
    wagering: z.string().optional(),
    wageringRequirements: z.string().optional(),
    minimumDeposit: z.string().optional(),
    withdrawalTimes: z.string().optional(),
    // Promotion specific
    exclusive: z.union([z.boolean(), z.string()]).optional(),
    expires_at: z.coerce.string().optional(),
    claim_url: z.string().optional(),
    website: z.string().optional(),
    // Extended fields
    casinoName: z.string().optional(),
    casinoType: z.string().optional(),
    currencies: z.string().optional(),
    depositMethods: z.string().optional(),
    withdrawalMethods: z.string().optional(),
    gameProviders: z.string().optional(),
    licences: z.string().optional(),
    established: z.number().optional(),
    liveChat: z.string().optional(),
    emailSupport: z.string().optional(),
    freeSpins: z.union([z.number(), z.string()]).optional(),
    freeSpinsCount: z.string().optional(),
    freeSpinsWr: z.string().optional(),
    bonusDuration: z.string().optional(),
    bonusPercentage: z.string().optional(),
    maximumBonusAmount: z.string().optional(),
    withdrawalLimit: z.string().optional(),
    withdrawalFees: z.string().optional(),
    minimumWithdrawalAmount: z.string().optional(),
    playerRating: z.number().optional(),
    vipLoyaltyProgram: z.string().optional(),
    affiliateProgram: z.string().optional(),
    casinoReviewUrl: z.string().optional(),
    company: z.string().optional(),
    excerpt: z.string().optional(),
    robots: z.string().optional(),
    noIndex: z.boolean().optional(),
    draft: z.boolean().optional(),
    featured: z.boolean().optional(),
    category: z.string().optional(),
    maxBonus: z.string().optional(),
    coverImage: z.string().optional(),
    createdAt: z.coerce.string().optional(),
    schemaJsonLd: z.string().optional(),
  }),
});

const news = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/news" }),
  schema: z.object({
    title: z.string(),
    slug: z.string(),
    description: z.string(),
    seoTitle: z.string(),
    tags: z.array(z.string()),
    publishedAt: z.coerce.string(),
    updatedAt: z.coerce.string().optional(),
    image: z.string(),
    imageAlt: z.string(),
    imageWidth: z.number().optional(),
    imageHeight: z.number().optional(),
    author: z.string(),
    authorSlug: z.string().optional(),
    canonical: z.string().optional(),
    schema_jsonld: z.union([z.array(z.any()), z.record(z.any()), z.string()]).optional(),
    contentType: z.string().optional(),
    featured: z.boolean().optional(),
    relatedPosts: z.array(z.string()).optional(),
  }),
});

const authors = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/authors" }),
  schema: z.object({
    name: z.string(),
    slug: z.string(),
    role: z.string(),
    bio: z.string(),
    expertise: z.array(z.string()).optional(),
    joinedAt: z.coerce.string(),
    image: z.string().optional(),
    social: z.object({
      twitter: z.string().optional(),
      linkedin: z.string().optional(),
    }).optional(),
  }),
});

export const collections = { bonuses, news, authors };
